// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RMS.Infrastructure.Persistence;

#nullable disable

namespace RMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260727135228_MakeSectionIdNullable")]
    partial class MakeSectionIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Permission", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("module_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("is_system_role")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("RMS.Core.Entities.AcademicYear", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_current")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("academic_years");
                });

            modelBuilder.Entity("RMS.Core.Entities.AdmissionEnquiry", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("child_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("father_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("admission_enquiries");
                });

            modelBuilder.Entity("RMS.Core.Entities.AlumniProfile", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("current_occupation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("current_organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("graduation_year")
                        .HasColumnType("integer");

                    b.Property<string>("higher_education_details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("alumni_profiles");
                });

            modelBuilder.Entity("RMS.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ip_address")
                        .HasColumnType("text");

                    b.Property<string>("new_values")
                        .HasColumnType("jsonb");

                    b.Property<string>("old_values")
                        .HasColumnType("jsonb");

                    b.Property<string>("record_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("table_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("RMS.Core.Entities.BookIssuance", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("book_id")
                        .HasColumnType("uuid");

                    b.Property<string>("borrower_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("fine_amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("issue_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("return_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("staff_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("book_issuances");
                });

            modelBuilder.Entity("RMS.Core.Entities.ClassSubject", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("passing_marks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("total_marks")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("id");

                    b.ToTable("class_subjects");
                });

            modelBuilder.Entity("RMS.Core.Entities.ExamMark", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("assignment_marks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("exam_setup_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_absent")
                        .HasColumnType("boolean");

                    b.Property<decimal>("obtained_marks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("practical_marks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("theory_marks")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("id");

                    b.ToTable("exam_marks");
                });

            modelBuilder.Entity("RMS.Core.Entities.ExamResult", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("exam_setup_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("gpa")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("total_max_marks")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("total_obtained_marks")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("id");

                    b.ToTable("exam_results");
                });

            modelBuilder.Entity("RMS.Core.Entities.ExamSchedule", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("end_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("exam_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("exam_setup_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("passing_marks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("start_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("total_marks")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("id");

                    b.ToTable("exam_schedules");
                });

            modelBuilder.Entity("RMS.Core.Entities.ExamSetup", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_locked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("exam_setups");
                });

            modelBuilder.Entity("RMS.Core.Entities.FeeChallan", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("academic_year_id")
                        .HasColumnType("uuid");

                    b.Property<string>("billing_month")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("challan_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("discount_amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("issue_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("late_fine")
                        .HasColumnType("numeric");

                    b.Property<decimal>("net_payable")
                        .HasColumnType("numeric");

                    b.Property<decimal>("paid_amount")
                        .HasColumnType("numeric");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("fee_challans");
                });

            modelBuilder.Entity("RMS.Core.Entities.FeeChallanDetail", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("base_amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("challan_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("discount_amount")
                        .HasColumnType("numeric");

                    b.Property<string>("fee_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("fee_type_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("net_amount")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("fee_challan_details");
                });

            modelBuilder.Entity("RMS.Core.Entities.FeeConcession", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("discount_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("discount_value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("fee_type_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("fee_concessions");
                });

            modelBuilder.Entity("RMS.Core.Entities.FeePayment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("challan_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("remarks")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("fee_payments");
                });

            modelBuilder.Entity("RMS.Core.Entities.FeeStructure", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("academic_year_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("fee_type_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("fee_structures");
                });

            modelBuilder.Entity("RMS.Core.Entities.FeeType", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("fee_types");
                });

            modelBuilder.Entity("RMS.Core.Entities.GradingScale", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("gpa_point")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("grade_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("max_percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("min_percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("grading_scales");
                });

            modelBuilder.Entity("RMS.Core.Entities.Holiday", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("holidays");
                });

            modelBuilder.Entity("RMS.Core.Entities.Homework", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("attachment_urls")
                        .HasColumnType("text");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("homework_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("max_marks")
                        .HasColumnType("integer");

                    b.Property<Guid>("section_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("staff_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id");

                    b.ToTable("homeworks");
                });

            modelBuilder.Entity("RMS.Core.Entities.HomeworkComment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("comment_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("homework_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("homework_comments");
                });

            modelBuilder.Entity("RMS.Core.Entities.HomeworkSubmission", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("attachment_urls")
                        .HasColumnType("text");

                    b.Property<Guid>("homework_id")
                        .HasColumnType("uuid");

                    b.Property<int?>("marks_obtained")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<string>("student_notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("submission_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("teacher_remarks")
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("homework_submissions");
                });

            modelBuilder.Entity("RMS.Core.Entities.HostelAllocation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("allocation_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("remarks")
                        .HasColumnType("text");

                    b.Property<Guid>("room_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("vacating_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("HostelAllocations");
                });

            modelBuilder.Entity("RMS.Core.Entities.HostelRoom", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("is_available")
                        .HasColumnType("boolean");

                    b.Property<decimal>("monthly_fee")
                        .HasColumnType("numeric");

                    b.Property<string>("room_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("room_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("hostel_rooms");
                });

            modelBuilder.Entity("RMS.Core.Entities.HousePointLog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("awarded_by")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("house_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("points")
                        .HasColumnType("integer");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("house_point_logs");
                });

            modelBuilder.Entity("RMS.Core.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .HasColumnType("text");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<int>("reorder_level")
                        .HasColumnType("integer");

                    b.Property<string>("supplier_name")
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("inventory_items");
                });

            modelBuilder.Entity("RMS.Core.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("issued_to")
                        .HasColumnType("text");

                    b.Property<Guid>("item_id")
                        .HasColumnType("uuid");

                    b.Property<string>("purpose")
                        .HasColumnType("text");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<string>("reference_number")
                        .HasColumnType("text");

                    b.Property<string>("remarks")
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("transaction_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("transaction_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("inventory_transactions");
                });

            modelBuilder.Entity("RMS.Core.Entities.LeaveApplication", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("applied_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("approver_id")
                        .HasColumnType("uuid");

                    b.Property<string>("approver_notes")
                        .HasColumnType("text");

                    b.Property<string>("attachment_url")
                        .HasColumnType("text");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("leave_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("staff_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("leave_applications");
                });

            modelBuilder.Entity("RMS.Core.Entities.LessonPlan", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<int>("completion_percentage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("target_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("teacher_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("lesson_plans");
                });

            modelBuilder.Entity("RMS.Core.Entities.LibraryBook", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("available_copies")
                        .HasColumnType("integer");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("isbn")
                        .HasColumnType("text");

                    b.Property<decimal?>("price")
                        .HasColumnType("numeric");

                    b.Property<int?>("publication_year")
                        .HasColumnType("integer");

                    b.Property<string>("publisher")
                        .HasColumnType("text");

                    b.Property<string>("shelf_location")
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("total_copies")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("library_books");
                });

            modelBuilder.Entity("RMS.Core.Entities.LiveClass", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("duration_minutes")
                        .HasColumnType("integer");

                    b.Property<string>("meeting_link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("teacher_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("live_classes");
                });

            modelBuilder.Entity("RMS.Core.Entities.Notice", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("published_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("target_audience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("id");

                    b.ToTable("notices");
                });

            modelBuilder.Entity("RMS.Core.Entities.OnlineExam", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("duration_minutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("exam_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("exam_setup_id")
                        .HasColumnType("uuid");

                    b.Property<int>("passing_marks")
                        .HasColumnType("integer");

                    b.Property<Guid?>("section_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("total_marks")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("online_exams");
                });

            modelBuilder.Entity("RMS.Core.Entities.OnlineExamQuestion", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("online_exam_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("question_bank_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("online_exam_questions");
                });

            modelBuilder.Entity("RMS.Core.Entities.QuestionBank", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<string>("correct_option")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("difficulty_level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("marks")
                        .HasColumnType("integer");

                    b.Property<string>("option_a")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("option_b")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("option_c")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("option_d")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("question_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("question_banks");
                });

            modelBuilder.Entity("RMS.Core.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("permission_id")
                        .HasColumnType("uuid");

                    b.HasKey("role_id", "permission_id");

                    b.HasIndex("permission_id");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("RMS.Core.Entities.SalarySlip", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("allowance_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("basic_salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("deduction_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("net_salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("payment_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("salary_month")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("staff_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("salary_slips");
                });

            modelBuilder.Entity("RMS.Core.Entities.SchoolClass", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("RMS.Core.Entities.SchoolExpense", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expense_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("recorded_by_user_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("school_expenses");
                });

            modelBuilder.Entity("RMS.Core.Entities.Section", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("max_capacity")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("room_number")
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("sections");
                });

            modelBuilder.Entity("RMS.Core.Entities.Staff", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("basic_salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("biometric_id")
                        .HasColumnType("text");

                    b.Property<string>("cnic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("joining_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rfid_card_id")
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("staff");
                });

            modelBuilder.Entity("RMS.Core.Entities.StaffAttendance", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("check_in")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("check_out")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("fine_amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("is_half_day")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_late")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("numeric");

                    b.Property<string>("location_address")
                        .HasColumnType("text");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid>("staff_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("staff_attendance");
                });

            modelBuilder.Entity("RMS.Core.Entities.Student", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("admission_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("admission_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("b_form_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("biometric_id")
                        .HasColumnType("text");

                    b.Property<string>("blood_group")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("father_cnic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("father_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("guardian_phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("house_name")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("parent_id")
                        .HasColumnType("uuid");

                    b.Property<string>("profile_picture_url")
                        .HasColumnType("text");

                    b.Property<string>("rfid_card_id")
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("wallet_balance")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudentAttendance", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("academic_year_id")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("check_in_time")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("check_out_time")
                        .HasColumnType("interval");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("fine_amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("is_half_day")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_late")
                        .HasColumnType("boolean");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("student_attendance");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudentBehaviorLog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("academic_year_id")
                        .HasColumnType("uuid");

                    b.Property<string>("action_taken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("incident_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("incident_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("points_affected")
                        .HasColumnType("integer");

                    b.Property<Guid>("reported_by_user_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("student_behavior_logs");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudentDiary", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<string>("conduct")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("homework_summary")
                        .HasColumnType("text");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("section_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("student_diaries");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudentEnrollment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("academic_year_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("roll_number")
                        .HasColumnType("integer");

                    b.Property<Guid>("section_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("student_enrollments");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudentExamAttempt", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("end_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_completed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("online_exam_id")
                        .HasColumnType("uuid");

                    b.Property<string>("responses_json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("student_exam_attempts");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudentMedicalRecord", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("additional_notes")
                        .HasColumnType("text");

                    b.Property<string>("allergies")
                        .HasColumnType("text");

                    b.Property<string>("chronic_conditions")
                        .HasColumnType("text");

                    b.Property<string>("doctor_name")
                        .HasColumnType("text");

                    b.Property<string>("doctor_phone")
                        .HasColumnType("text");

                    b.Property<string>("emergency_contact_name")
                        .HasColumnType("text");

                    b.Property<string>("emergency_contact_phone")
                        .HasColumnType("text");

                    b.Property<string>("emergency_contact_relation")
                        .HasColumnType("text");

                    b.Property<string>("family_medical_history")
                        .HasColumnType("text");

                    b.Property<DateTime>("last_updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("vaccination_status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("student_medical_records");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudentSubject", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_elective")
                        .HasColumnType("boolean");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("student_subjects");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudentSubjectAttendance", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("timetable_period_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("student_subject_attendance");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudentTransport", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("pickup_point")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("route_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("student_transport");
                });

            modelBuilder.Entity("RMS.Core.Entities.StudyMaterial", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("file_url")
                        .HasColumnType("text");

                    b.Property<string>("material_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("uploaded_by")
                        .HasColumnType("text");

                    b.Property<string>("video_url")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("study_materials");
                });

            modelBuilder.Entity("RMS.Core.Entities.Subject", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<bool>("is_elective")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("RMS.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("fiscal_year_start")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("login_background_url")
                        .HasColumnType("text");

                    b.Property<string>("logo_url")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<string>("primary_color")
                        .HasColumnType("text");

                    b.Property<string>("principal_name")
                        .HasColumnType("text");

                    b.Property<string>("registration_no")
                        .HasColumnType("text");

                    b.Property<string>("school_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("school_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("subdomain")
                        .HasColumnType("text");

                    b.Property<string>("website")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("RMS.Core.Entities.TimetablePeriod", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("day_of_week")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("end_time")
                        .HasColumnType("interval");

                    b.Property<string>("room_name")
                        .HasColumnType("text");

                    b.Property<Guid>("section_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("staff_id")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("start_time")
                        .HasColumnType("interval");

                    b.Property<Guid>("subject_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("timetable_periods");
                });

            modelBuilder.Entity("RMS.Core.Entities.TimetableProxyAllocation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("absent_staff_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("allocated_by")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("date_of_proxy")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("substitute_staff_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("timetable_period_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("timetable_proxy_allocations");
                });

            modelBuilder.Entity("RMS.Core.Entities.TransportRoute", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("end_point")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("monthly_fee")
                        .HasColumnType("numeric");

                    b.Property<string>("route_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("start_point")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stops")
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("vehicle_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("transport_routes");
                });

            modelBuilder.Entity("RMS.Core.Entities.TransportVehicle", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("driver_license_number")
                        .HasColumnType("text");

                    b.Property<string>("driver_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("driver_phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("vehicle_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("vehicle_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("transport_vehicles");
                });

            modelBuilder.Entity("RMS.Core.Entities.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .HasColumnType("text");

                    b.Property<string>("profile_picture_url")
                        .HasColumnType("text");

                    b.Property<string>("refresh_token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("refresh_token_expiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("two_factor_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("two_factor_secret")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("RMS.Domain.Common.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RMS.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("Permission", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Role", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
